### ISSUE TITLE
Further configuration tracking

### ISSUE THREAD

**Issue by cmroughan** [Princeton-CDH/htr2hpc#20]
Determine whether there is a useful method of programmatically tracking the following:

- [ ] celery worker counts
- [ ] celery worker details
- [ ] local redis 
- [ ] active thread count (if useful)

If there is not good programmatic access to these stats when running tests, determine an appropriate workflow so that the current stats are consistently tracked for different runs of testing.
